version: '3.7'
services:  
  mysqldb:    
    image: mysql:8.0.19
    container_name: aqa-mysql
    ports:      
      - '3306:3306'    
    environment:      
      - MYSQL_RANDOM_ROOT_PASSWORD=yes      
      - MYSQL_DATABASE=app      
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    